### ISSUE TITLE
category based streams

### ISSUE THREAD

**Issue by edsu** [edsu/wikistream#28]
I got this feature suggestion from Daniel Mietchen, who is working in the [Wikimedian in Residence for Open Science] (http://meta.wikimedia.org/wiki/User:Mietchen/Wikimedian_in_Residence_on_Open_Science) program:

> Do you have any plans to add category support to Wikistream? I am particularly interested in having such a display for pages in Category:Science, its subcategories and, if possible, its counterparts in other languages.

It would be a great feature to have, but would currently require pinging the various wikipedia APIs for every update, which would generate a lot of traffic. A possibly better approach would be to update the mediawiki code to emit the article's categories when dumping the status message in IRC.

**Comment by skierpage** [comment]
Looking at maintenance/tables.sql, the `recentchanges` table just doesn't have the category information, so someone would have to do a query of the categories of the page. Furthermore, it seems you can't action=query&prop=categories for an old revision of a page, you always get the categories of the latest version. So it would be hard to get category additions.

**Comment by edsu** [comment]
Ok, this has been open long enough. :-)
