### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by intracer** [edsu/wikistream#48]
http://wikistream.wmflabs.org/ does not open last days with "Error 503 Backend fetch failed"

**Comment by edsu** [comment]
I'm checking with the Wikimedia Labs folks to see what's going on. I'm currently unable to ssh into the server where the service is running.

**Comment by edsu** [comment]
It's back...for now.

**Comment by intracer** [comment]
Does not work again since Oct 8. Is there any way to monitor and fix outages?

**Comment by edsu** [comment]
Thanks for noticing @intracer I've reopened the [Wikimedia Labs ticket](https://phabricator.wikimedia.org/T232486). There are some suggestions in there about things that could be done to improve the uptime. It seems like when it is rebooted the service isn't coming back? 

Just out of curiosity what do you use wikistream for?

**Comment by intracer** [comment]
Some admins use it for fighting vandalism

**Comment by edsu** [comment]
It looks like it's back up & running again. I'd be curious to hear how you use it for fighting vandalism, I thought there were other more specialized tools?

**Comment by intracer** [comment]
To watch recent edits. What other more specialized tools do you mean?

**Comment by edsu** [comment]
Thanks. I always assumed there were other tools for looking at recent edits...
